### ISSUE TITLE
Email Fabio asking for permission to use various libraries

### ISSUE THREAD

**Issue by Winwardo** [Winwardo/solid-octo-disco#25]
React
Express
Babel for ES6
OrientDB
Webpack
Semantic-UI

Anything else @VasilyShelkov?

**Comment by VasilyShelkov** [comment]
dev dependencies:
-gulp for task running
-mocha/chai for testing
-jscs and airbnb eslint config for autoformatting
-nodemon for file watching and restarting node server automatically during development
-istanbul/codacy-coverage for test coverage

**Comment by VasilyShelkov** [comment]
Also going to ask whether we could use Redux and explicitly say that in the front end it decouples the presentational aspects of the web app from the data retrieval and actions so that if we know now whether we can or can't use it. Thoughts @Winwardo ?

**Comment by Winwardo** [comment]
Don't forget the important js-builder-decorator!!!

Redux is fine if he thinks its fine and you can argue for it.

**Comment by VasilyShelkov** [comment]
@Winwardo this ok ? Each library is in a bulleted list and links to their respective homepage in case he wants to check any of them himself.

Hi Fabio,

For the assignment, are we able to use these third party libraries:
-ReactJS - alternative to AngularJS for front-end development
-Express - you have said that we can use it since it was in the lecture but just explicitly stating
-Babel for ES6 - so we can use es6 syntax in both the server and client code
-Webpack - to build, bundle, transpile with Babel and minify into a build file for the server and a build file the client code.
-OrientDB - for storing the data
-Semantic-UI - Alternative to bootstrap, purely used for the styling of the interface to save writing a lot of CSS that we won't be marked on anyway
-js-builder-decorator - used to consolidate different sources of the same type of data ie tweets from twitter and from our database

3rd Party Development Tools:
-Gulp - task running and automating workflow
-Mocha/Chai for testing
-Jscs and airbnb eslint config - for autoformatting and keeping codebase consistent.
-Nodemon - file watching and restarting node server automatically during development
-Istanbul/Codacy-coverage - test coverage

Lastly we're not sure whether it'll be helpful to use it due to being so early in the project, but if we choose to, could we use React-Redux which we've found helps to decouple web interface 'presentation components' from the actions that they may perform such as adding a type of search query or sorting data in a different way. If not then we won't even consider it.

Many Thanks.
Solid-Octo-Disco 👌 (Topher Winward and Vasily Shelkov)

**Comment by VasilyShelkov** [comment]
I'll forward you the email and you can close this issue if you send it X))

**Comment by Winwardo** [comment]
Hi Fabio,

I asked you about this in person during the last lab session, but I wanted to confirm the use of the following free open-source packages for solid-octo-disco 👌's Intelligent Web assignment.

Core packages:
-ReactJS; alternative to AngularJS for front-end development
-Express; for serving on top of Node.js more simply 
-Twit; For easier Twitter API access
-Babel for ES6; so we can use ES6 / JavaScript 2015 syntax in both the server and client code
-Webpack; to build, bundle, transpile with Babel and minify into a build file for the server and a build file the client code
-OrientDB; a graph/document database for storing the tweets / tweeters and finding interesting links
-Semantic-UI; alternative to Bootstrap, purely used for the styling of the interface to save writing a lot of CSS that we won't be marked on anyway
-js-builder-decorator; a small library Topher wrote for generating builder patterns for objects. (This is available on npm to anyone publically)

3rd party tools used during development:
-Gulp; task running and automating workflow
-Mocha/Chai; for unit/integration testing
-JSCS and Airbnb ESLint config; for autoformatting and keeping codebase consistent.
-Nodemon; file watching and restarting node server automatically during development
-Istanbul; test coverage

Other services:
-Travis CI; for externally building and testing the program independently
-Codacy; which consolidates many static analysers into one service and automatically finds potential bugs and issues in the project ( see here https://www.codacy.com/app/winwardo/solid-octo-disco/dashboard )

Lastly we're not sure whether it'll be helpful to use it due to being so early in the project, but if we choose to, we'd like to use React-Redux which we've found helps to decouple web interface 'presentation components' from the actions that they may perform such as adding a type of search query or sorting data in a different way. If not then we won't even consider it.

Let us know if there's any problem with any of the above libraries, and see you tomorrow.

Many thanks,
Team solid-octo-disco 👌 (Topher Winward and Vasily Shelkov)

**Comment by Winwardo** [comment]
Email sent.
