### ISSUE TITLE
Search query object definition

### ISSUE THREAD

**Issue by Winwardo** [Winwardo/solid-octo-disco#47]
{'query': 'some string'}

at the minimum, although obviously there'll be a lot more depth to it.
@VasilyShelkov comment as you get a better idea of what you want to send from #4 
#46 will need to keep up with the latest version of this.

**Comment by VasilyShelkov** [comment]
first draft object def and what'll be initially used.:
[
  { query: 'someWord', 
    paramType:['hashtag', 'keyword', 'author', 'mention'],
    source: 'twitter' 
  }, {
  ...
  }
]

There can only be one source per query... ie can't have source: ['twitter', 'facebook'] otherwise will have to figure out what paramType is from where and there may be similiar named paramtypes between social networks that will have to be interpreted differently
