### ISSUE TITLE
Method of choosing between calling Twitter and our DB

### ISSUE THREAD

**Issue by VasilyShelkov** [Winwardo/solid-octo-disco#48]
query each search term individually to our DB and check the latest result if older than X then search twitter.

**Comment by Winwardo** [comment]
Usefully, Twitter has a "search since".
That is, if the newest result in our database is older than X (say 30 minutes) THEN we actually search the Twitter API, using :since (most recent tweet)
This can save on Twitter calls, as well as it being a suggestion in the Assignment spec :+1: 

"as a cache to reduce the number of queries sent to the Twitter API. This means that in case of
repeated queries, the database must provide the data already made available by the past
queries and the Twitter API must be used to retrieve only the additional data that should
have become available since the previous queries were issued."
